name: Build Image
on:
  push

jobs:
  building_from_file:
    name: Container creation
    runs-on: self-hosted
    steps: 
      - run: | 
          buildah bud -f Dockerfile -t gtc:${{ github.sha }}
          
  
  testing_container:
    name: locally running the container + possible smoke tests 
    runs-on: self-hosted
    steps:
      - run: | 
          podman run -p 8081 --name gtc gtc:${{ github.sha }}
          echo "is the container running? $(podman inspect gtc | jq -r '.[].State.Running')"
          echo "Publish port: $(podman inspect gtc | jq -r '.[].NetworkSettings.Ports|.[]|.[]|.HostPort')"
          echo "Testing the endpoint"
          curl localhost:$(podman inspect gtc | jq -r '.[].NetworkSettings.Ports|.[]|.[]|.HostPort')/Feature1
          echo "sanity checks done, stopping container.."
          podman stop gtc
  publishing_image:
    name: image push to  docker.hub registry 
    runs-on: self-hosted
    steps:                 
      - run: | 
          skopeo login docker.io
          skopeo copy containers-storage:localhost/gtc:${{ github.sha }}[4] docker://microlotf/hellogo:${{ github.sha }}
