name: Build Image
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image : gtc
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
