name: Build Image
on:
  push

jobs:
  building_from_file:
    name: Container creation
    runs-on: self-hosted
    steps: 
      - run: | 
          buildah bud -f Dockerfile -t gtc:${{ github.sha }}
          
  
  smoke_tests:
    name: locally running the container + possible smoke tests  
    runs-on: self-hosted
    needs: building_from_file
    steps:
      - run: | 
          podman run -d -p 8081 --name gtc localhost/gtc:${{ github.sha }}
          curl localhost:$(podman inspect gtc | jq -r '.[].NetworkSettings.Ports|.[]|.[]|.HostPort')/Feature1
          podman rm gtc
  publishing_image:
    name: image push to  docker.hub registry 
    runs-on: self-hosted
    needs: smoke_tests
    steps:                 
      - run: | 
          skopeo login docker.io
          skopeo copy containers-storage:localhost/gtc:${{ github.sha }} docker://microlotf/hellogo:${{ github.sha }}
